language: c

env:
  global:
    - secure: "fKtWSvdzPU1u0kL9SmwXpDnmLLEdjYA/1vMlg0B3HqiVisgw+ecqAW1sMrzf\narhmygGGNivigyJ4/pV7AtEG7nXFzjUHqjMwsbvBW0Im1uUoQ8pKGrQCdE8B\nBHNApZNXPaZe7c/N8vR3+6wEW1SG25plnJ//x/4iudDoFV5AXEU="

compiler:
  - gcc

before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig cmake colordiff postgis postgresql-9.1-postgis-2.0-scripts libpq-dev libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-noxpm-dev libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
  - cd msautotest
  - ./create_postgis_test_data.sh
  - cd ..

script:
  - ./run-test-suite.sh

after_success: 
  - echo "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true"; then echo "run coverage"; ./run_code_coverage_upload.sh; fi'

notifications:
#  email:
#    recipients:
#      - thomas.bonfort@gmail.com

  irc:
    channels:
      - "irc.freenode.org#mapserver"
    use_notice: true

