language: c

compiler:
  - gcc

before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpq-dev libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-noxpm-dev libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev libxml2-dev
  - sudo apt-get install php-pear
  - sudo pear config-set auto_discover 1 && sudo pear install --alldeps channel://pear.phpunit.de/PHPUnit
  - echo "extension=php_mapscript.so" | sudo tee -a /etc/php5/cli/php.ini

install:
  - ./configure --with-gd --with-postgis --with-wmsclient --with-wfsclient --with-kml --with-cairo --with-wcs --with-proj --with-geos --with-gdal --with-ogr --with-wfs --with-sos --with-php
  - make -j4
  - sudo make install 
  - sudo ldconfig

script:
  - ./runtests.sh

notifications:
  email:
    recipients:
      - thomas.bonfort@gmail.com

  irc:
    channels:
      - "irc.freenode.org#mapserver"
    use_notice: true
