language: c

env:
  global:
#    - secure: "fKtWSvdzPU1u0kL9SmwXpDnmLLEdjYA/1vMlg0B3HqiVisgw+ecqAW1sMrzf\narhmygGGNivigyJ4/pV7AtEG7nXFzjUHqjMwsbvBW0Im1uUoQ8pKGrQCdE8B\nBHNApZNXPaZe7c/N8vR3+6wEW1SG25plnJ//x/4iudDoFV5AXEU="
     - secure: "dWb9nnvPdglptNQ/y7AGXTc9RAQ2JEbQSRBCOMsaO8CsRa/MAuIj/WRzNgCK\nFO5ovpd96+ZqPwAxHILos5Dj4uAga0d+9P+bqYedtnVcmPtsuwmh6TKmPUi3\n7KYMCzQLh05Gwm8lSPTFfFCFH2as2XzaRLa28ED7QoTWmdbNu7E="
     - secure: "IdBl0V3EOesXK1tHa916xAA5AhNYAgc50pChbbGBkwwuVGe/t7J9bsPQZfLU\n52l1S6J79ulEVZurXSjFE1m7gSm64V3zNADaMrHv/zFqNznq+lBlrOq8pfO0\nm9XRdRYqGY6dmhvv8vp7mAGoAvbXqV2JQGJ9eqSMHh/fhTGWSE8="
     - secure: "nJMbbZOAyA55BZTTb2OuFiC6Prb1pMHoK/Eg/0Q6k1OgFBMveLbjuvwH+mb9\n50tnAZ6w1ergbNfcdcy+1I3zDVF05Anu0hIz2AP1j9jqhrVUPW88ItarN/VK\n74A0p2c86ArbZ7UU4zbvGI09GkvoStIeKx91OAiZndLnVNGq2QA="
     - secure: "B9CwMd7w1ry4jBsViEU0gsOVcq8Cylf8CeunLWe7L1P+wIRaJIKB6sVBgdzb\nN5oGgBNECyVG8sK8Y5U8dYhm6LX9xjmTf4aFZYQfZB1rXJNtqB+I0iEULdMS\nJ+q33qB8BK28aiKlLHBEpnV9aotEAz294niDKyqkxAOgHP/3RaU="
     - secure: "UdAp41dm7mn9q8c1/5Ekay7gY+86DEiI6UDvgyk/r3sv62PWefzOLoc63Sl5\nO+x/daXyIWYlrhL+y0vqOfjquL5QPDhYXEiL9OB+fFZniJAGP9wCy2xbQdKO\nn5zU7JgS6lwbbien2bjdaThewI7edttbnVBpd3jX2MontfOD9kI="
     - secure: "iFy/WosABW+E7l91kvth9nkjCnUDPn7nB2ytVYWqOvdz4Pw38tccvAzPV8ID\n+jPaKL2e4L6hXDv6JVariWVL94+Ij11TKPaFr+jI1J1O1+A4l/J298BLVJKq\nEE4AunP7Tu1AnVP46oyngrUfcD6n/s86WBOQodLCz2T7R0bHpjk="
     - secure: "c6SWncNq8G/t31UwmTNZ3j605LManZiiWIJfAKA2aJ5s6L/I121ZSkYGz629\nVUqTXhkjBrUxlMeN2fJST0aaAn5q1KPLJxUd50aZb6scuoTlkMHYNnzNZEF2\n8JjW5zrPfuq9MLfYPsB+iDhk29e8uEIO653CZwdJ+QSoKtl15ko="
     - secure: "euEZf2z8j5zYywEH0hd/qMKENixgaffyVr36EKo4ulR8avh7Xe6qu2NUNKDr\nIPsAvdMS0PZdjiVbKbkF2FWFciX2hmXspwfjEyCbYI9/eLzZI8Ikan9HQGnz\nkfUQyN+Rtf2qbSSTp7+KhQOMa0YPWhyB/t+z+XOm3Z+ScvsULn0="
     - secure: "UFKJ0q5ReZbgWrF5nFprzwYxHJN63imiTRRKuouXo7Z0u2rnVjynKCDjHtqg\nz56L22KPQqgs0eleC4Wlcz6TvAEo17RECNUw/QKU+Ipg5MK47WgNqK1bHXFM\nkZlhHHrgI7m4TOAiH2h9D3btlRCwkVw6jcQc4y+Aos/E9341Nrw="
     - secure: "SsYuSaRi7s+IW6kLibFzvCbVosu8r0w5s/Z6I/9wAkvKeallYqml2k7NGJJf\nAfQgwghaWjvlNNw1q7mUFp+qMQOptUS6ZIYNQYWjLsElfEWPMMTxXGx6YuQj\nMjI0+PIk4VeeeaRj7aAVESWyeXzAeVOHxxHUPpmcwDzq+/dwWQY="
     - secure: "LTh0qMRvC38ZmdktenFisO4zJB3q6dFH8bvXxZY1fkeg/KAkduveHBZ6E9KP\nOjLBlCO2Nr5xefIN99jVsSD9S8zJd+udFMAKIVBi+lqxs78liqB6IwAtQX2M\ndVipKk4IhkQl93vjFdhJycpOamL9qXhBBdZ0aJdzDcevqC+yjgI="
     - secure: "ONBAxr+Tx6D8n5arl8wMBK6O8etHn9OnhKiNEFYpK/L9VBunSoHKo5VP+8yk\nxo8D4BIn1ojNx2esaidNGi95BFiWgKQ7EQtaD4Uss7JtKWvHncRJAkr1ug4w\nblFNF5EqsTOlJpaYtaa8mKfe9eIBaPpH9e0y//TuLa2vS8v4gV8="
     - secure: "JBFk5dy+FEcFDb6PVUKwVGC4CN8UQ0FqwcP6aBH4E9BUUAGUNIUgUNL05P6W\nJDy6Fw+pnwQIFIGjMImf1E6sqMYQoiLfNKX0lUytRGDzLj+oQiw2RQ1w0VM0\nYfhx2NJHuWGRIpNXQKnXokO7MQ9cOpMLuTLiWpTMsh5HItXI56g="
     - secure: "WTC1nibOQbP+2d9V1zfQGHzJp618kzLL6cPTEYbzKvlaC3xpUQEfKKYvUFFr\nZrgxgZ4T8qPsfdlypMiZjg4aRnIlxc16QTOSo1EDuoXZu4mlUDShZuxhQqVq\n3gRr+0o4rMX+I9u62sOpToV0NzUCumAghJlUQAfgmFm9ihLNREM="
     - secure: "PRjQraVjE7dcRaQbOyd1p3/8fCnUXS8fAv4ABqB0W7Zr0P9U/XFISG5vxjQ0\npuVpUvsnrx11ZjyZKaxgRQu/JBibfvvv05g2YIfxGj68gLZC2FlwkLjxZYeK\ntus2odkSu6YQaKwZHUOES5l8LOkixMutDpGR3f2QBRgO8VcTWQ4="
     - secure: "ER1ZChyiqX/PPquIqyUzup6V10HoF2MfyKj91aTuXci3g3Nt8EsT6fZvoff3\nIqdaPY2eMrY0t+r3dODNpryroXxD8/Tm4eiRDZ5zyvEsVrG9TftUekgQ6MR2\nNMwGdWIZ5xVwwjGYp4tUy4dHg/MVVuaFT9iVR6tGmBoHAYgCfKQ="
     - secure: "K21le+tQ2R3sm5hbcjger3WsSKVlHLqZCNAnMSnW6ACa85StTJ62CF++apNf\n/VUfY1NM3R1v3jNRBXnqe7C0ZOjulxbexDi0FfkzgQDlBj2EwN1SA/z6z3cU\nlP9WlsOU+j51CMewi5lKvs/cHLN2kQoJQ9afkAIfOOZBdALWBGs="
     - secure: "DjwHSBjRbOX9j61yaSl+BmZTwGI4/8vzuN3oYWkyklc4rCcTDQsXAsVdf7sc\nKuYs5XUl76zcmZC+Obrlg220Out4ISOcsOjpDM/AOTAQOuxq7QuIhvIvCe36\n99KTBwLTyXgJAXL+BO8FsV5MgYo3dknnZ0jTgUkTgFBr6TMe7UI="
     - secure: "Ba+Rrcc2hSoD2193uRmUnBPOnVpGLq/YbOHBPmaG7kqPG/PRacCDTLsBuxdJ\ng7R01aMjP+TgKe6w8GrCMGhpZnNaUV2GmaYTMo2pbyVtD4iEEgZAa4doHfFJ\nUuuBPp4oWyPNkFIMvc4KE3Nezc2EixlMK8FCsGUhsaZMMe36Cvk="
     - secure: "EqRudlCUGCM2So+qdsUIoIlzXt72CYXm3dpCKxFby/H5jrJVtrV1jRLVb3rk\n54DqcJchjm6LJMM08m8kI+zDdA5Atlf2ke6QxlDwzF9aDnoQWKdMVoFxi9vp\nJXlAL8jKlDuCaeRxADIu1DDl5XmHIPqxzexSCtLal0kp8+gF1rU="
     - secure: "Bvfpwm7zPWcYVNYmk8iXDXbY4HBnPTx+kicMA5RxvJLBrjxQxPHXunzvn5jT\nj7JFlWWlTZQH+XG7E8bDYtyXF9rw0a5XMelY1nImIMPurBW7q9no6SbEnc/O\n3rWlGqsKmG+gnvm97kAItGiklnmkE3iu4iVCDMNfDRiSmGd9i0s="
     - secure: "L/aM4N/JZjN/xIDhGvIFx6c/e7mLiXoW0Pa2YGR3uDI3nX6CxqDGv7vnzYO8\ns3PVk3BTzK9nDnVdWGhnEmJkyp5lpG1Ei4xSa3MLAui1tQAr7JouJP1gKfbY\n87ihb4XBBFdqTLz0IzAMXUDSewlxjLWEo7Qnf4JFaJmMq29R3J8="
     - secure: "BxI1PXGLhW+IJLD96UQp8PHm5RGzELK1sGS5jM/A3GXua2t+e7tjB2SCvE5p\nSQ1O0QfBA4tuuNVIBawb+nW45fmpD/zLVdeifIa6KDnZhbr+LLL40WyleoR0\nKXzeyiX/zhcwTc9TaWggL/sl/USgwCOHl+SK2eoPxjL1ThnwvLk="
     - secure: "YFCpypMzA4Vr1t8D8VUA1zYo1Rt+ZkMKeU9qD92H1ZSzH4jWo4w3ljUPrCd2\nVT+U/8mZgovfemj2aM6bFhxHjkl2X9OKCSBOGN0OZ7/vswsPN2fAPgD4bcu8\naPcHr45e90MQUXKSNF2qUvKku5KWqOGI6p/khH/gkxIBea8XLpA="
     - secure: "dja/Zsh97QRGElYeWp/16t3QxqNCnDw+Np0Lli9Gsn44sJC0HTc+8KTujRET\nqmxz9E++WY/hkW+wd/TTnVjCzxbqKH4HHW+2BMBcmHB7AsG/gGDzMSjLa/Gl\nN71wGTjPV06r9sjD176CRFQGXrxZHTFXRH1Wa+kTEC1YNKYpF0E="
     - secure: "VaIVd781cclYO2O0Nm/0ufXBiGjDzKaxgeJbUIv9X+e5oEUQ39bUIiOLN4Yq\nFEu7dDceppGCtFiM7M6iuRe2rF8jcb3lKZo0tbRIq0YSbpsgggc9PD5DDSN6\n1yERaA77mBs6s7l1PZEv+VTqr0c2uuJatsCDO8p4vf2ogERJl8c="
     - secure: "hLV+B+y+QVV5//zkTrjdPN710cN0zINf48F7Wi9AUewx4zemW0AQWgfQbCA9\nNpb8Dyg9W3PXrPNRK0Og8zEazlkAjh4564qV83q5kEv88vrReKI6PMvw4r+t\nPL2INYfFHicRFpWORzxJtMTdW4/aDmg+RR0LEOfKpbXqwMIr/fg="
     - secure: "pHxt1ILgYg0QcMD4QPkeG70BwnNI9LpSpg+WFQgHfLYpn18Svq1131EyTXhV\nmPSjJSEidFsIDjUhtqwBLD5bD8CxcelFtYSITMMBe3xr4ZzlLA1F4EitmQJW\nDPUPZD994MTfs63ELEWHzTrzyen1X2S0omFISaDqgB21wNv8ntc="
     - secure: "NtywBGOy3PE2PQoyBgFmvF4+riV7Z0d2QDufRRlas/2AcWfxsDKNLlSIPC+w\nI+a7Ldrfofhiuf6Qef7Z52IbEgJ8CkdX1+pbgHf8tBNffMp9jkU3b53fg5zo\nPWOR1CA08UfcDQunb2Q1bHmJe5T8OddDCGlTOdcp+i/I5M4/aSA="
     - secure: "p59qrSerP5VSOKtw8UeGcsxVYeWJUv5kVqry4gdwaBhy6YSKoi0EHzTWzAGI\n/COHnl+MkpJT9K9VvsP/a1OTIDr11sv6eaRH113eZg+VfqqGMPqF8z7VX30D\nMqQ/KPsctFftx+eGqqb6aerLg3PT3Umv83OXFU7r0dNJeU+I91w="

compiler:
  - gcc

#before_install:
#  - git submodule update --init --recursive
#  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq swig cmake colordiff postgis postgresql-9.1-postgis-2.0-scripts libpq-dev libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-noxpm-dev libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
#  - cd msautotest
#  - ./create_postgis_test_data.sh
#  - cd ..

#script:
#  - ./run-test-suite.sh

#after_success: 
script:
  - echo "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true"; then echo "run coverage"; ./run_code_coverage_upload.sh; fi'

notifications:
#  email:
#    recipients:
#      - thomas.bonfort@gmail.com

  irc:
    channels:
      - "irc.freenode.org#mapserver"
    use_notice: true

