language: c

env:
  global:
#    - secure: "fKtWSvdzPU1u0kL9SmwXpDnmLLEdjYA/1vMlg0B3HqiVisgw+ecqAW1sMrzf\narhmygGGNivigyJ4/pV7AtEG7nXFzjUHqjMwsbvBW0Im1uUoQ8pKGrQCdE8B\nBHNApZNXPaZe7c/N8vR3+6wEW1SG25plnJ//x/4iudDoFV5AXEU="
     - secure: "pFpZRbsrNB3Jn3Jz5iwRwnIyGIVqBO9Si/uZ5h0tHoOIlzO4bqFqhJU5gd9B\nLqZVvAfrnChRLcoF/WH8r2VuAtuoLJ6LZglL6dSchAMcaVcUx1dVBhzSgjR1\nKBuBhj6A7QA2+mDsuhJyCjN8UbPcEP53zIJCMgoPQNIqqmx4o1s="
     - secure: "VWnLdgulPKPrsMFvW/QRdlxPvWxVElJHYlQhNzxuYWIebf6jaCffJCJSbLRE\nQmGYC0D2nZZCzfiYieCW1kVcF3Do2bRGhN/xbUyMC7/qLLVFTlwHumPR7BAr\nl9VMpjJnRY6A8clOuE34HdCc0IUz9Actq7+dozQhzQRi6iEKFIQ="
     - secure: "iMko4inN+TU1gq0dhm6BNyAW3AiIkrDLeierkpPP186hsXoDwckziswv4Myg\n7MyDr/WDkhMUtSY+bDaQfdU64vAe+p3LOIcbRsHkqlAicQ0WJ1mZM7Za5fEo\n+kb0JRV5+pzz7cLzw/I+7Vx/zBhStyot14MLPsQPQc5417O8sJM="
     - secure: "bqOSLkLYkSb/5CSNPde7V+MWgcB7u1mrQfVZv4HvDVcKYoMZn9ejnT9cuKk7\nWlvGy8xLt5lcXYqXO/5LwegnChtwz/KTxHzTv1SdvahWhBP8C59Qk8qWGDLK\nydXJOZVR3tbm3f5QhWUWiiLl1tvVaVMX9UUkw8f4tzqJOh8Qaeo="
     - secure: "BvDGpG2dJEeA3VDteP/fVXV3xtxldZRrNCPd1ZzUgk/sa2ye2Feej4csJv6a\njcZuePLA6g6yI0cJvZnoBPePfKTmunOAisKiCwcBxOES/M3XdLmCh6ca3TzK\n12CvJbywTt8JC+l+46rZpQT77Zd9Lx2EXTjreE1m+BLJ/gaSXXg="
     - secure: "HUjaNbEKkjhck+iuz5kgaF7zVJ8UIVuDYJ3/a3G9Gzxn4lPJOVc15kz9ider\n589oY3FKzpbqQv6+KIzMImgRIaH8J2PaXf8Fdl/NwQHd1HkYYrW4TLJkqNSP\nLb8nzvSTkFcuny93X86tuM8UQNnL+KqgJFqtAQmliLUO7XYxacQ="
     - secure: "Ou3vtlQguDuhXS+N4glSnsa8SCmzzeBWK3x06ir28OGnUG/mruzoxWKH540J\nfw86n+CwMHRqSYtr9Tes/eBV9SMe9ZbeMIUY4PMnydJpEotW8mblm6fte5bD\nuwwBlILqd0sB5FLS641qRgmPzCfIB9t4IG9w1zUigv4AAXFPxF8="
     - secure: "H0CTvJQBSlplnxWidSS8nz51B4GWN9stqJ78AiFZLrpWkfswwSCgpMlAu3e/\njgIxBt/zqQOYzZIuwpiQ7ENbFQElbO6ggqve7rfJ9+48vGlbZ+Vh3EuBGbbq\nQU00edMPeGfxsOjgmPc3b+ojcpToMSM0SOZIpXmDnWyWLp8f7SU="
     - secure: "Vc8k/eAGtvjMC/ZbsG0N7eLqZ8QfugwTcW1G7d9dYsxQ8gx68farpq+x7Z1c\n5ygA4b5Ovx9iFzxuRbunXBvKQGKAeKzBTPEY1n7hy9lNc5AbQrRpYnK3xpTv\nGBh3UWVO3Gzkqi6eQWKu016QA9f26j4QbL3CoKAzPkLAVfn3T5A="
     - secure: "XC5yrlhBLYRP0sgcCpNiBj+JpJCUq43gPqaqvhP2xRVAmfsjdeNYKe39yhQ6\n5Z1A+svNGBijx72bE6PiyaWMuvtmkfhEoxcLqkmxmly0eDalAfFT2x6chzjY\nlz29jLS2yF6Ha0n1eeHK21bZmGPqvhWux+w5Z+wVnq5WmeqgsH8="
     - secure: "Pn3tu4wdyFycaiUx2KsvbjIMs7GzQQdf0VbZ2DcND8chIWtwcWcWwsOmT5fV\nQTzkeq3o6+gf6Y7Bq1rmOsw9Gst9I0WKj0evF6N+OTL8dPA1Z7ahenav2afN\n/rMbW3Isaowy/c00gt/1Y0wE96B0VEykyjqRUs59wFE3E1BN+gU="
     - secure: "Do/d9mRSbA+PgtaskobXyyxL4ElBRFEjaNZQvTTfH6bEsh23hb3fhffS0H5r\n4PvPAjaptP8Ybg2cpQlP9Rekr9/XvSOL4NmhtteO7laub9ybpEMZoqZ/dM1j\nePu+rd6JovMIFhVuaqiPLTDAqujedKX92Mu3SN9BHpxidCFofsU="
     - secure: "VBzTc1RWZhBHOVDcEHF9cHJTzJpzpGNxwlvy9mX8OBSKYQoZUBI7HbjQt35m\nKXTz30h+IPs7Z8kR7lCL8zm9LQHzz3oyZ5AgMyk3vGY1k/cGJBM3sx9fTeNf\nuHmd7Si36NyU7AJGJSKVh5zkiGg+qC+Ge1Dl/3DMWo5iMLbHgXY="
     - secure: "cRu8Xjz5emYejf/sHxDpe21SdOun1ZzuRzir3DTK/yFEucyzr16p92WaTMie\nQXHDrfsW5JpMrvq27Rzlmzeybarde+29lkxY4yAypyWixAfH3ySJ1rC8gVWT\n98nmxnu6u7+yVPT+O1wOzWqstj8F2RQmUp3C9c7kwnOU4jxObD4="
     - secure: "FFLC1ExnMWl7PT3OZMoiwEaNmTnHbV/t9yr4qNOkDI6q+0ZurYZ7or5jSmrD\nRcwWflChCaKeqQaYJNGjBnEjgISPz3sPAynICM/cKx+R5FTkHZFmd4hVQVjC\nuDItRAx7DSQAsnG7zDgryQJcNfQ0wzEObf+wP+zkCBT9EEPMxM8="
     - secure: "K8QM4ls0d60Q6rblf1kNe8a7iVx+h3BSeQ8iEFT207Pa6vHZwhIYNesaOBU8\nSJO49bWdsb/r8z3dlhWNxQvYT7tjfMBwjFIJS6ENpN+c2vUli8AwxagcLF+r\nfdIaTSemfJuxboe0i7GZz3WfCVB2oLsDbACF2AFcLLkDsVWvR5M="
     - secure: "XckBqAtcwPZiaQehjlTeYixJMGfbn/fWEDkDetGCCvmG60YV9mYdo+uRe1t/\n8bDUfZBNjMYRh8uigXXLkOJPULlcMRMlt4TUQHtG7dPUJSaNYx+vIpd3kiiv\nTXegYZJ8EAxejzhEG3wez2iQXHyX2/qqUalgPnKVdWJ7KxELw0k="
     - secure: "R3PEYUckO+CT2Sz3kX1JhHwtpN1ElXKUq6iS3KuxPEdUItY6YQOZxJSQdndc\nCU7GHRuSGAZ3ngxjBiHQWDQB+BhEKt4cD8oxBq9YSgGb5srNZbJJoOWa6ypc\nTdwhgg/eWsFtYj4TIEedPeyRa5prZ8JvEXyqCTnTP0Ntg+oUf3Y="
     - secure: "mImYt2geH71BN0+qLe6cRskUyFJtlG+T5bT7tZzEL76E27xlqTCwooqiOV/L\nc0ZXpt5cO1qVBy4KBtyYpMWBGd6h8Vtytq/IsCAfDk6e9P+aqc6tHvqfSt60\nZBk9plMw+IutcsAz3laQ8VGri36KVoa0PHggzBz5wIUdtpYZb54="
     - secure: "lDKvUlibZrs3dQlyTW84VpisKCLu5VU5OFn5ht7QwOW8wCoQXodEbusXpolR\n6TVioViz/a2EWZoXbyTbxsVopsYI6RG/e4GNO6tTX+WuO9/Q6RMeiS3CbLNT\nWRuHAXoHJE2cv06aAf/qOI6yWjZW1k/uXeFTubggY0kNOrzzUiY="
     - secure: "cPn0ZTCN3aK1WlRdXDna0q1oibBpC0puojr2s16hOetVt+PFYbCH3m178+9d\n3+4q3YAYhQ0HMS6nMed0N6wr85VrJwjwvzJrr0oITT4clU/tsqM55bQjSm1S\nECLmAYqs1gIb72hJtu+/ibaBSuAVyii2Uru94UynnhviL45Ux4Y="
     - secure: "FoToW32izZ8h0aynu/JRve2Nr7C75s8LJCSKbmpTXNV5tf3+bnn7hs6bow6h\nlbznV0zmguJ7T8IOxrbJ1eP9RhA3rwO+rLxaONbMe4nGPXHp37mI9mYq7sbj\nLL0IYzcVcvxho0V9iRrpx4ySjx8fYSusZh/u9wsgaelO/EmpB14="
     - secure: "VcFd3oHgsRbDxd5myioeNQz11a7jqqnAc/BNStMibVcC7WNdrmI5bAdXbl0o\nTiOv32tVeVoHr7kGGBcQltHbai2K/TABAmmiDQmjquo63pW23cCvNfDiyLvm\nBj0K2INToyUBcrWwKCvZpzxAXHmxV0xz+poJW4oVxU4Gcbmkj/k="


compiler:
  - gcc

#before_install:
#  - git submodule update --init --recursive
#  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq swig cmake colordiff postgis postgresql-9.1-postgis-2.0-scripts libpq-dev libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-noxpm-dev libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
#  - cd msautotest
#  - ./create_postgis_test_data.sh
#  - cd ..

#script:
#  - ./run-test-suite.sh

#after_success: 
script:
  - echo "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true"; then echo "run coverage"; ./run_code_coverage_upload.sh; fi'

notifications:
#  email:
#    recipients:
#      - thomas.bonfort@gmail.com

  irc:
    channels:
      - "irc.freenode.org#mapserver"
    use_notice: true

